# Generated by Django 4.2.3 on 2023-07-27 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_remove_group_student_id_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_have',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='group.group'),
        ),
    ]
