# Generated by Django 4.2.3 on 2023-08-03 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField(default=0)),
                ('room_type', models.CharField(choices=[('1', 'Small'), ('2', 'Middle'), ('3', 'Big')], max_length=30)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('subject_taught', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('Small degree', '1'), ('Middle degree', '2'), ('Big degree', '3')], max_length=40)),
                ('teacher_img', models.ImageField(blank=True, null=True, upload_to='teacher_img/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('time', models.CharField(max_length=10)),
                ('lesson_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lessonroom')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.subject')),
                ('teach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.teacher')),
            ],
        ),
    ]
