# Generated by Django 4.2.3 on 2023-07-31 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableitem',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='tableitem',
            name='week',
        ),
        migrations.AddField(
            model_name='table',
            name='shift',
            field=models.CharField(choices=[('1', '1-Para'), ('2', '2-Para'), ('3', '3-Para')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='table.week'),
            preserve_default=False,
        ),
    ]
