# Generated by Django 4.2.3 on 2023-08-03 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_tableitem_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='table.tableitem'),
            preserve_default=False,
        ),
    ]
